#!/usr/bin/ env bash
#configures nginx to port 80

#Removing the default Nginx configuration file
rm/etc/nginx/sites-enabled/default

#cconfigure nginx to listen on port 80 for all active ipv4 IP's
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
#restarting nginx
service nginx restart
